name: Check and Add Footer

on: [push, pull_request]

jobs:
  check-footer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check Last Commit Message
      id: check_commit
      run: |
        commit_message=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" \
          | jq -r '.commit.message')

        expected_message="Automation: Update README.md Quote"

        if [ "$commit_message" == "$expected_message" ]; then
          echo "Quote already updated."
          exit 1
        else
          echo "Quote not updated."
          exit 0
        fi

    - name: Set up Python
      if: steps.check_commit.outcome == 'success'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Dependencies
      if: steps.check_commit.outcome == 'success'
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Script to Check and Add Footer
      if: steps.check_commit.outcome == 'success'
      run: |
        python footer/footer-update.py

    - name: Commit changes
      if: steps.check_commit.outcome == 'success'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Add footer to markdown files" || echo "No changes to commit"
        git push