name: Update README with daily quote

on:
  workflow_dispatch:
  schedule:
    - cron: '1 0 * * *'  # Everyday at 00:00

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests googletrans==4.0.0-rc1 deep_translator

      - name: Run scripts/update-quote.py
        run: |
          python scripts/update-quote.py

      - name: Check for changes
        run: |
          git status
          git diff

      - name: Commit changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git add README-br.md
            git commit -m "Automation: Update README.md Quote"
            git push
          fi
